repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        additional_dependencies: ["toml"]
-   repo: https://github.com/ambv/black
    rev: 20.8b1 # Use the revision sha / tag you want to point at
    hooks:
    - id: black
      additional_dependencies: ["toml"]
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0 # Use the revision sha / tag you want to point at
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      exclude: src/leet