"""
8.4 Bucket sort
===============

Bucket sort assumes that the input is drawn from a uniform distribution and has an
average-case running time of O(n). Whereas counting sort assumes that the input consists
of integers in a small range, bucket sort assumes that the input is generated by a
random process that distributes elements uniformly and independently over the interval
[0, 1).

Bucket sort divides the interval [0, 1) into n equal-sized sub-intervals, or buckets,
and then distributes the n input numbers into the buckets. Since the inputs are
uniformly and independently distributed over [0, 1), we do not expect many numbers to
fall into each bucket. To produce the output, we simply sort the numbers in each bucket
and then go through the buckets in order, listing the elements in each.

NB: Counting sort cannot be used here since we use the keys as indices in counting sort.
In bucket sort, the keys are floating point numbers.

Bucket sort is stable if the underlying sort is stable.

Complexity
==========

Time
----

bucket_sort(): O(n)/O(n^2) average/worst case using insertion sort.

Space
-----

bucket_sort(): O(n) for the B array of buckets.
"""

# Repository Library
from src.clrs.sorting_and_order_statistics.sorting.comparison_sorting.insertion_sort import (  # noqa: E501
    insertion_sort,
)


def bucket_sort(a):
    n, x = len(a), []
    b = [[] for _ in range(n)]
    for i in range(n):
        b[int(n * a[i])].append(a[i])
    for i in b:
        if i:
            insertion_sort(i)
            x.extend(i)
    return x


def bucket_sort_ints(a, num_buckets=5):
    amin, amax = min(a), max(a)
    b_range, b, x = (amax - amin) / num_buckets, [[] for _ in range(num_buckets)], []
    for i in a:
        diff = (i - amin) / b_range - int((i - amin) / b_range)
        print(diff, i, amin, b_range)
        if diff == 0:
            b[int((i - amin) / b_range) - 1].append(i)
        else:
            b[int((i - amin) / b_range)].append(i)
    for i in b:
        if i:
            insertion_sort(i)
            x.extend(i)
    return x


a = [9.8, 0.6, 10.1, 1.9, 3.07, 3.04, 5.0, 8.0, 4.8, 7.68]
print(bucket_sort_ints(a))
